### ISSUE TITLE
TensorFlow roadmap

### ISSUE THREAD

**Issue by altavir** [mipt-npm/kmath#433]
- [ ] Add advanced mathematic operations / implement AnalyticTensorAlgebra
- [ ] Add TensorFlowExpression an expression builders in a scope
- [ ] Store/visualize graph
- [ ] Restore expressions/outputs from file
